version: '2'
services:
  admin02-app:
    image: admin02
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://admin02-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=admin02
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  admin02-mongodb:
    extends:
      file: mongodb.yml
      service: admin02-mongodb
